version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./deploy/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./deploy/certbot/www/:/var/www/certbot/:ro
      - ./deploy/certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./deploy/certbot/www/:/var/www/certbot/:rw
      - ./deploy/certbot/conf/:/etc/letsencrypt/:rw
      - ./deploy/certbot/conf/live/:/etc/nginx/ssl/live/d
  django:
    build:
      context: .
      dockerfile: cosmetic_meow_backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    restart: always

  react-app:
    build:
      context: .
      dockerfile: cosmetic_meow_frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: always