# Generated by Django 4.1.10 on 2024-01-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, verbose_name='')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('type', models.CharField(choices=[('T', 'Обучение'), ('S', 'Магазин'), ('O', 'Другое'), ('D', 'Контрактное производство')], default='O', max_length=1, verbose_name='Тип обратной связи')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
                'ordering': ['-id'],
            },
        ),
    ]
