# Generated by Django 4.1.10 on 2023-08-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isMethodist',
            field=models.BooleanField(default=False),
        ),
    ]
