# Generated by Django 5.0.3 on 2024-03-05 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='ProductActiveSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClinicalTestingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountPrice',
            fields=[
                ('baseprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cosmetic_meow_api.baseprice')),
                ('begin_date', models.DateField(verbose_name='Дата начала действия скидки')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия скидки')),
            ],
            bases=('cosmetic_meow_api.baseprice',),
        ),
        migrations.CreateModel(
            name='BasePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(verbose_name='Дата изменения')),
                ('old_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic_meow_api.baseprice', verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClinicalTestingResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('product_clinical_testing_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic_meow_api.productclinicaltestingresult', verbose_name='Результаты клинических испытаний')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('product_lines', models.ManyToManyField(to='cosmetic_meow_api.productline', verbose_name='Линии продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='cosmetic_meow_api.baseprice', verbose_name='Цена')),
                ('active_substances', models.ManyToManyField(to='cosmetic_meow_api.productactivesubstance', verbose_name='Активные вещества')),
                ('advantages', models.ManyToManyField(to='cosmetic_meow_api.productadvantage', verbose_name='Преимущества')),
                ('clinical_testing_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic_meow_api.productclinicaltestingresult', verbose_name='Результаты клинических испытаний')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic_meow_api.productline', verbose_name='Линия продукта')),
                ('discount_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_price', to='cosmetic_meow_api.discountprice', verbose_name='Цена со скидкой')),
            ],
        ),
    ]
