# Generated by Django 4.1.10 on 2023-08-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_course_students_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['id'], 'verbose_name': 'сертификат', 'verbose_name_plural': 'сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='contentfile',
            options={'ordering': ['id'], 'verbose_name': 'файл контента', 'verbose_name_plural': 'файлы контента'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursestudent',
            options={'ordering': ['purchase_date'], 'verbose_name': 'курс для пользователя', 'verbose_name_plural': 'курсы для пользователей'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['id'], 'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='training/certificates/'),
        ),
    ]
